///////////////////////////////////////////////////////////////////////////////
// Copyright (C) 2026 Jean-Philippe Steinmetz
// SPDX-License-Identifier: MPL-2.0
///////////////////////////////////////////////////////////////////////////////
import { x509 } from "./runtime.js";
import * as crypto from "node:crypto";
import { childrenOf, readTlv, spkiKeyBits } from "./certutil.js";
import { OID } from "./oids.js";
import { derNull, derOid } from "./der.js";
import type { CertificateType } from "./CertificateBuilder.js";
import { bytesEqual, fromB64url, pemBlocks, sha256Hex, toArrayBuffer, toBytes } from "./util.js";
import { canonicalMailbox, readDerUtf8String, SMTP_UTF8_MAILBOX_OID } from "./mailbox.js";
import { AsnConvert } from "@peculiar/asn1-schema";
import { SubjectAlternativeName } from "@peculiar/asn1-x509";

/** The largest CSR (in octets) that is even parsed; an RSA-8192 request with a SAN list is well under 4 KiB. */
export const MAX_CSR_OCTETS = 32 * 1024;
/** The most e-mail addresses a single CSR may name before it is rejected as abusive. */
export const MAX_CSR_EMAILS = 100;

/**
 * A request or key that violates this CA's issuance policy. Carries the ACME problem the caller should answer with:
 * `badCSR` (RFC 8555 s6.7: the CSR is unacceptable) or `badPublicKey` (the key is weak, unsupported or forbidden).
 *
 * @author Jean-Philippe Steinmetz
 */
export class PkiPolicyError extends Error {
    public readonly code: "badCSR" | "badPublicKey";

    /**
     * @param code The ACME error type suffix.
     * @param message A human-readable, client-safe explanation.
     */
    public constructor(code: "badCSR" | "badPublicKey", message: string) {
        super(message);
        this.name = "PkiPolicyError";
        this.code = code;
    }
}

/** The result of a successful {@link validateCsr}. */
export interface ValidatedCsr {
    /** Canonical DER SubjectPublicKeyInfo: the only thing that is ever copied from a CSR into a certificate. */
    spki: Uint8Array;
    /** Lower-case hex SHA-256 of {@link ValidatedCsr.spki}. */
    spkiSha256: string;
    /** The key family. */
    keyKind: "rsa" | "ec";
    /** e.g. "RSA 3072" or "ECDSA P-256". */
    keyDescription: string;
    /** The requested mailboxes (rfc822Name or SmtpUTF8Mailbox) as canonical `local@A-label-domain`, order preserved, duplicates removed. */
    emails: string[];
    /** From the KeyUsage extension request (RFC 8823 s3.3); `undefined` when the CSR does not request key usages. */
    requestedType?: CertificateType;
}

const KU_SIGNING = 0x01 | 0x02; // digitalSignature | nonRepudiation
const KU_RSA_ENCRYPTION = 0x04; // keyEncipherment
const KU_EC_ENCRYPTION = 0x10; // keyAgreement
const OID_EXTENSION_REQUEST = "1.2.840.113549.1.9.14";

function badCsr(message: string): PkiPolicyError {
    return new PkiPolicyError("badCSR", message);
}

function badKey(message: string): PkiPolicyError {
    return new PkiPolicyError("badPublicKey", message);
}

/** Short, printable rendering of untrusted text for an error message. */
function show(value: unknown): string {
    return JSON.stringify(String(value).slice(0, 80));
}

/** Primes below 752: the Baseline Requirements' bound for "no small prime factors" of an RSA modulus. */
const SMALL_PRIMES: number[] = (() => {
    const sieve = new Uint8Array(752);
    const primes: number[] = [];
    for (let i = 2; i < 752; i++) {
        if (!sieve[i]) {
            primes.push(i);
            for (let j = i * i; j < 752; j += i) {
                sieve[j] = 1;
            }
        }
    }
    return primes;
})();

/**
 * For the ROCA (CVE-2017-15361, Infineon RSALib) fingerprint: for each of the first odd primes q below 354, the set of
 * residues that powers of 65537 take modulo q. Keys generated by the flawed library have primes of the form
 * `k * M + 65537^a mod M` with M a primorial, so their modulus lies in that subgroup for *every* such q; a random
 * modulus does so with probability well below 2^-100.
 */
const ROCA_RESIDUES: Array<{ q: bigint; residues: Set<bigint> }> = (() => {
    const out: Array<{ q: bigint; residues: Set<bigint> }> = [];
    for (const q of SMALL_PRIMES) {
        if (q === 2 || q > 353) {
            continue;
        }
        const residues = new Set<bigint>();
        let x = 1n;
        const g = 65537n % BigInt(q);
        do {
            residues.add(x);
            x = (x * g) % BigInt(q);
        } while (x !== 1n);
        // Skip primes where 65537 generates the whole group: they say nothing about the modulus.
        if (residues.size < q - 1) {
            out.push({ q: BigInt(q), residues });
        }
    }
    return out;
})();

/** Floor of the k-th root of n (Newton's method from above). */
function integerRoot(n: bigint, k: number): bigint {
    const kk = BigInt(k);
    let x = 1n << BigInt(Math.ceil(n.toString(2).length / k));
    for (;;) {
        const y = ((kk - 1n) * x + n / x ** (kk - 1n)) / kk;
        if (y >= x) {
            return x;
        }
        x = y;
    }
}

const PRIME_EXPONENTS: number[] = (() => {
    // Primes up to 862: a modulus of at most 8192 bits that is a prime power p^k has p >= 757, so k <= 8192 / 9.5.
    const sieve = new Uint8Array(900);
    const out: number[] = [];
    for (let i = 2; i < 900; i++) {
        if (!sieve[i]) {
            out.push(i);
            for (let j = i * i; j < 900; j += i) {
                sieve[j] = 1;
            }
        }
    }
    return out;
})();

/**
 * Checks an RSA public key against the Baseline Requirements' (and NIST SP 800-89) modulus/exponent rules. Kept
 * separate from parsing so that every rule is an explicit, testable statement.
 *
 * @param n The modulus, big-endian without leading zeros.
 * @param e The public exponent, big-endian without leading zeros.
 * @param deep `false` skips the two expensive tests (perfect power, ROCA fingerprint: tens of milliseconds at 8192 bits), so a
 * caller can reject a structurally bad key at once and run them only once the key has proved it can sign.
 * @returns A string describing the key on success.
 * @throws PkiPolicyError badPublicKey on any violation.
 */
function checkRsa(nBytes: Uint8Array, eBytes: Uint8Array, deep: boolean): string {
    if (nBytes.length === 0 || nBytes[0] === 0) {
        throw badKey("RSA modulus is not minimally encoded");
    }
    const bits = (nBytes.length - 1) * 8 + (32 - Math.clz32(nBytes[0]));
    if (bits < 2048 || bits > 8192) {
        throw badKey(`RSA keys must be 2048 to 8192 bits (got ${bits})`);
    }
    if (bits % 8 !== 0) {
        throw badKey("RSA modulus length must be a multiple of 8 bits");
    }
    const n = BigInt("0x" + Buffer.from(nBytes).toString("hex"));
    if ((n & 1n) === 0n) {
        throw badKey("RSA modulus must be odd");
    }
    if (eBytes.length === 0) {
        throw badKey("RSA public exponent missing");
    }
    const e = BigInt("0x" + Buffer.from(eBytes).toString("hex"));
    if ((e & 1n) === 0n || e < 65537n || e >= 1n << 256n) {
        throw badKey("RSA public exponent must be odd and between 65537 and 2^256-1");
    }
    for (const p of SMALL_PRIMES) {
        if (n % BigInt(p) === 0n) {
            throw badKey("RSA modulus has a small prime factor");
        }
    }
    if (!deep) {
        return `RSA ${bits}`;
    }
    const kMax = Math.floor(bits / 9.5);
    for (const k of PRIME_EXPONENTS) {
        if (k > kMax) {
            break;
        }
        const r = integerRoot(n, k);
        if (r ** BigInt(k) === n) {
            throw badKey("RSA modulus is a perfect power");
        }
    }
    if (ROCA_RESIDUES.every(({ q, residues }) => residues.has(n % q))) {
        throw badKey("RSA key matches the ROCA (CVE-2017-15361) weak-key fingerprint");
    }
    return `RSA ${bits}`;
}

const EC_CURVES: Record<string, string> = {
    prime256v1: "ECDSA P-256",
    secp384r1: "ECDSA P-384",
    secp521r1: "ECDSA P-521",
};

/**
 * Applies the key policy to a DER SubjectPublicKeyInfo: RSA 2048-8192 bits (modulus a multiple of 8 bits, odd,
 * exponent odd and 65537 to 2^256-1, no prime factor below 752, not a perfect power, not the ROCA fingerprint) or
 * ECDSA on P-256/P-384/P-521 (Node/OpenSSL has validated that the point is on the curve). The encoding must also be
 * the canonical DER one: an SPKI that re-encodes differently (explicit curve parameters, compressed points, BER length
 * forms, trailing data) is refused, because it is about to be copied verbatim into a certificate.
 *
 * @param spki DER SubjectPublicKeyInfo.
 * @throws PkiPolicyError badPublicKey when the key is unacceptable.
 */
export function checkPublicKey(spki: Uint8Array, o: { deep?: boolean } = {}): { keyKind: "rsa" | "ec"; description: string } {
    if (!(spki instanceof Uint8Array) || spki.length === 0 || spki.length > 2048) {
        throw badKey("SubjectPublicKeyInfo has an invalid size");
    }
    let key: crypto.KeyObject;
    try {
        key = crypto.createPublicKey({ key: Buffer.from(spki), format: "der", type: "spki" });
    } catch {
        throw badKey("The public key is not a valid SubjectPublicKeyInfo");
    }
    const canonical = new Uint8Array(key.export({ type: "spki", format: "der" }));
    if (!bytesEqual(canonical, spki)) {
        throw badKey("The public key is not in canonical DER form (or uses explicit/compressed parameters)");
    }
    // Node reports the named curve even for an SPKI that spells the curve out as explicit parameters, and re-exports it
    // unchanged, so the canonical-form check above does not catch that; check the AlgorithmIdentifier directly.
    let algorithmOid: Uint8Array;
    let parameters: Uint8Array;
    try {
        const outer = readTlv(spki, 0);
        const algorithm = childrenOf(spki, outer)[0];
        const [oid, params] = childrenOf(spki, algorithm);
        algorithmOid = spki.subarray(oid.start, oid.end);
        parameters = params ? spki.subarray(params.start, params.end) : new Uint8Array();
    } catch {
        throw badKey("The public key is not a valid SubjectPublicKeyInfo");
    }
    if (key.asymmetricKeyType === "rsa") {
        if (!bytesEqual(algorithmOid, derOid(OID.rsaEncryption)) || !bytesEqual(parameters, derNull())) {
            throw badKey("RSA keys must use rsaEncryption with NULL parameters");
        }
        const jwk = key.export({ format: "jwk" });
        if (typeof jwk.n !== "string" || typeof jwk.e !== "string") {
            throw badKey("Malformed RSA public key");
        }
        return {
            keyKind: "rsa",
            description: checkRsa(new Uint8Array(Buffer.from(jwk.n, "base64url")), new Uint8Array(Buffer.from(jwk.e, "base64url")), o.deep !== false),
        };
    }
    if (key.asymmetricKeyType === "ec") {
        const description = EC_CURVES[key.asymmetricKeyDetails?.namedCurve ?? ""];
        if (!description) {
            throw badKey(`Unsupported elliptic curve ${show(key.asymmetricKeyDetails?.namedCurve)} (use P-256, P-384 or P-521)`);
        }
        const namedCurveOid = { prime256v1: OID.prime256v1, secp384r1: OID.secp384r1, secp521r1: OID.secp521r1 }[
            key.asymmetricKeyDetails!.namedCurve as string
        ]!;
        if (!bytesEqual(algorithmOid, derOid(OID.ecPublicKey)) || !bytesEqual(parameters, derOid(namedCurveOid))) {
            throw badKey("EC keys must name their curve by object identifier (no explicit parameters)");
        }
        // Only the uncompressed point form: OpenSSL keeps a compressed point compressed on re-export, so the
        // canonical-form comparison above cannot see it, and clients differ in their support for compression.
        const point = spkiKeyBits(spki);
        const expectedLength = { prime256v1: 65, secp384r1: 97, secp521r1: 133 }[key.asymmetricKeyDetails!.namedCurve as string];
        if (point.length !== expectedLength || point[0] !== 0x04) {
            throw badKey("The public key is not in canonical DER form (compressed EC point)");
        }
        return { keyKind: "ec", description };
    }
    throw badKey(`Unsupported public key type ${show(key.asymmetricKeyType)} (use RSA or ECDSA)`);
}

const TYPES: readonly CertificateType[] = ["signing", "encryption", "signing-encryption"];

/**
 * Combines the certificate type implied by the CSR's KeyUsage request (RFC 8823 s3.3) with the `profile` of the
 * order (draft-aaron-acme-profiles).
 *
 * The CSR decides what is issued; the profile is a ceiling on it. A CSR without a KeyUsage request adopts the
 * profile (or, with neither, gets both usages). A request the profile does not cover (the CSR wants an encryption
 * usage under the `signing` profile, or wants both under a single-purpose profile) contradicts the order and is
 * rejected instead of being silently narrowed or widened. A narrower CSR under the broad `signing-encryption` profile
 * gets exactly what it asked for.
 *
 * @param requested The type implied by the CSR, or `undefined` when it carries no KeyUsage request.
 * @param profile The order's profile, if any.
 * @throws PkiPolicyError badCSR when the two contradict each other or a value is not a known type.
 */
export function resolveCertificateType(
    requested: CertificateType | undefined,
    profile: CertificateType | undefined
): CertificateType {
    if ((requested !== undefined && !TYPES.includes(requested)) || (profile !== undefined && !TYPES.includes(profile))) {
        throw badCsr("Unknown certificate type");
    }
    if (requested === undefined) {
        return profile ?? "signing-encryption";
    }
    if (profile === undefined || profile === "signing-encryption" || requested === profile) {
        return requested;
    }
    throw badCsr(`The CSR's key usages request a '${requested}' certificate, which contradicts the order's '${profile}' profile`);
}

/** Total length of the first DER TLV of `bytes` (header included), or -1 when the header is malformed. */
function derTotalLength(bytes: Uint8Array): number {
    if (bytes.length < 2 || bytes[0] !== 0x30) {
        return -1;
    }
    if (bytes[1] < 0x80) {
        return 2 + bytes[1];
    }
    const count = bytes[1] & 0x7f;
    if (count === 0 || count > 4 || bytes.length < 2 + count) {
        return -1;
    }
    let length = 0;
    for (let i = 0; i < count; i++) {
        length = length * 256 + bytes[2 + i];
    }
    return 2 + count + length;
}

function decodeInput(csr: Uint8Array | string): Uint8Array {
    if (typeof csr === "string") {
        const text = csr.trim();
        if (text.includes("-----BEGIN")) {
            let blocks;
            try {
                blocks = pemBlocks(text);
            } catch {
                throw badCsr("The CSR PEM is malformed");
            }
            if (
                blocks.length !== 1 ||
                (blocks[0].label !== "CERTIFICATE REQUEST" && blocks[0].label !== "NEW CERTIFICATE REQUEST")
            ) {
                throw badCsr("Expected exactly one CERTIFICATE REQUEST PEM block");
            }
            return blocks[0].der;
        }
        try {
            return fromB64url(text);
        } catch {
            throw badCsr("The CSR is not valid base64url");
        }
    }
    if (!(csr instanceof Uint8Array)) {
        throw badCsr("The CSR must be bytes or a string");
    }
    return csr;
}

/**
 * Parses and validates a PKCS #10 certificate request for issuance.
 *
 * Accepts DER bytes, a PEM string, or an unpadded base64url string of the DER (the ACME `finalize` encoding). It
 * enforces: DER framing without trailing data, a valid proof-of-possession signature with an RSA-PKCS#1 v1.5 or ECDSA
 * algorithm over SHA-256/384/512 (no SHA-1, no PSS), the key policy of {@link checkPublicKey}, the caller's
 * revoked-key list, and exactly one SAN extension made only of well-formed `rfc822Name` entries. KeyUsage requests
 * are translated to a certificate type as RFC 8823 s3.3 specifies; a request for any usage other than
 * digitalSignature/nonRepudiation/keyEncipherment/keyAgreement, an encryption usage the key cannot perform (RSA
 * `keyAgreement`, EC `keyEncipherment`), an empty KeyUsage, or `CA:TRUE` is rejected. The subject and every other
 * requested attribute or extension are ignored; nothing but the public key is ever carried into the certificate.
 *
 * @param csr DER, PEM or base64url DER.
 * @param o `forbiddenSpkiSha256`: hex SHA-256 digests of SPKIs to refuse (the ACME account key, keys revoked for keyCompromise).
 * @throws PkiPolicyError `badCSR` for a bad request, `badPublicKey` for a bad key.
 */
export async function validateCsr(
    csr: Uint8Array | string,
    o?: { forbiddenSpkiSha256?: Iterable<string> }
): Promise<ValidatedCsr> {
    const der = decodeInput(csr);
    if (der.length === 0 || der.length > MAX_CSR_OCTETS) {
        throw badCsr("The CSR has an invalid size");
    }
    if (derTotalLength(der) !== der.length) {
        throw badCsr("The CSR is not a single DER SEQUENCE (trailing data or BER encoding)");
    }

    let req: x509.Pkcs10CertificateRequest;
    try {
        req = new x509.Pkcs10CertificateRequest(toArrayBuffer(der));
    } catch {
        throw badCsr("The CSR cannot be parsed");
    }

    const sigAlg = req.signatureAlgorithm as { name?: string; hash?: { name?: string } };
    const hash = sigAlg.hash?.name;
    if (
        (sigAlg.name !== "RSASSA-PKCS1-v1_5" && sigAlg.name !== "ECDSA") ||
        (hash !== "SHA-256" && hash !== "SHA-384" && hash !== "SHA-512")
    ) {
        throw badCsr("Unsupported CSR signature algorithm (use RSA PKCS#1 v1.5 or ECDSA with SHA-256/384/512)");
    }

    const spki = toBytes(req.publicKey.rawData);
    // The cheap key rules first (a structurally bad key is refused at once), then the signature, and only then the expensive
    // modulus tests (perfect power, ROCA: tens of milliseconds at 8192 bits, synchronously): they must not be spent on a request
    // that cannot even prove possession of its key.
    checkPublicKey(spki, { deep: false });
    let signatureOk = false;
    try {
        signatureOk = await req.verify();
    } catch {
        signatureOk = false;
    }
    if (!signatureOk) {
        throw badCsr("The CSR signature does not verify (no proof of possession of the private key)");
    }
    const { keyKind, description } = checkPublicKey(spki);
    if ((sigAlg.name === "ECDSA") !== (keyKind === "ec")) {
        throw badCsr("The CSR signature algorithm does not match its public key");
    }

    const spkiSha256 = sha256Hex(spki);
    if (o?.forbiddenSpkiSha256) {
        for (const forbidden of o.forbiddenSpkiSha256) {
            if (typeof forbidden === "string" && forbidden.toLowerCase() === spkiSha256) {
                throw badKey("This public key may not be used for a certificate (already in use or compromised)");
            }
        }
    }

    // --- Extensions ------------------------------------------------------------------------------------------
    if (req.getAttributes(OID_EXTENSION_REQUEST).length > 1) {
        throw badCsr("The CSR has more than one extensionRequest attribute");
    }
    const sans = req.getExtensions(OID.subjectAltName);
    if (sans.length !== 1 || !(sans[0] instanceof x509.SubjectAlternativeNameExtension)) {
        throw badCsr("The CSR must contain exactly one subjectAltName extension");
    }
    // Read the raw SAN: @peculiar/x509 does not model the SmtpUTF8Mailbox otherName (RFC 8398) that an internationalized address needs.
    let sanNames: SubjectAlternativeName;
    try {
        sanNames = AsnConvert.parse(sans[0].value, SubjectAlternativeName);
    } catch {
        throw badCsr("The subjectAltName extension cannot be parsed");
    }
    const emails: string[] = [];
    for (const name of sanNames) {
        let claimed: string | undefined;
        if (name.rfc822Name !== undefined) {
            claimed = name.rfc822Name;
        } else if (name.otherName !== undefined && name.otherName.typeId === SMTP_UTF8_MAILBOX_OID) {
            claimed = readDerUtf8String(new Uint8Array(name.otherName.value));
        } else {
            throw badCsr("Unsupported subjectAltName type: only rfc822Name and SmtpUTF8Mailbox are allowed");
        }
        const mailbox = canonicalMailbox(claimed);
        if (mailbox === undefined) {
            throw badCsr(`${show(claimed)} is not an acceptable e-mail address`);
        }
        if (!emails.includes(mailbox.canonical)) {
            emails.push(mailbox.canonical);
        }
    }
    if (emails.length === 0) {
        throw badCsr("The subjectAltName extension names no e-mail address");
    }
    if (emails.length > MAX_CSR_EMAILS) {
        throw badCsr("The CSR names too many e-mail addresses");
    }

    const basic = req.getExtensions(OID.basicConstraints);
    if (basic.length > 1 || (basic[0] !== undefined && !(basic[0] instanceof x509.BasicConstraintsExtension))) {
        throw badCsr("The CSR has an unusable basicConstraints extension");
    }
    if ((basic[0] as x509.BasicConstraintsExtension | undefined)?.ca) {
        throw badCsr("The CSR requests a CA certificate");
    }

    const kus = req.getExtensions(OID.keyUsage);
    if (kus.length > 1) {
        throw badCsr("The CSR has more than one keyUsage extension");
    }
    let requestedType: CertificateType | undefined;
    if (kus.length === 1) {
        const usages = kus[0] instanceof x509.KeyUsagesExtension ? (kus[0].usages) : undefined;
        if (usages === undefined || !Number.isInteger(usages) || usages <= 0) {
            throw badCsr("The CSR's keyUsage extension requests no usages");
        }
        const encryptionBit = keyKind === "rsa" ? KU_RSA_ENCRYPTION : KU_EC_ENCRYPTION;
        const other = usages & ~(KU_SIGNING | encryptionBit);
        if (other !== 0) {
            const names = ["keyEncipherment", "keyAgreement", "dataEncipherment", "keyCertSign", "cRLSign", "encipherOnly", "decipherOnly"];
            const unsupported = [0x04, 0x10, 0x08, 0x20, 0x40, 0x80, 0x100]
                .map((bit, i) => ((other & bit) !== 0 ? names[i] : undefined))
                .filter((n) => n !== undefined)
                .join(", ");
            throw badCsr(
                `The CSR's keyUsage requests ${unsupported}, which is not allowed for a ${description} S/MIME key (allowed: digitalSignature, nonRepudiation, ${
                    keyKind === "rsa" ? "keyEncipherment" : "keyAgreement"
                })`
            );
        }
        const wantsSigning = (usages & KU_SIGNING) !== 0;
        const wantsEncryption = (usages & encryptionBit) !== 0;
        if (!wantsSigning && !wantsEncryption) {
            throw badCsr("The CSR's keyUsage extension could not be interpreted");
        }
        requestedType =
            wantsSigning && wantsEncryption ? "signing-encryption" : wantsSigning ? "signing" : "encryption";
    }

    return { spki, spkiSha256, keyKind, keyDescription: description, emails, requestedType };
}
